"""empty message

Revision ID: 592bc3ee67e0
Revises: 
Create Date: 2018-06-29 18:18:17.117491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592bc3ee67e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('res_dist', sa.Float(), nullable=True),
    sa.Column('res_decsn', sa.Boolean(), nullable=True),
    sa.Column('res_same_per', sa.Float(), nullable=True),
    sa.Column('res_forg_per', sa.Float(), nullable=True),
    sa.Column('res_diff_per', sa.Float(), nullable=True),
    sa.Column('signature_1', sa.String(length=50), nullable=False),
    sa.Column('signature_2', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_timestamp'), 'test', ['timestamp'], unique=False)
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ref_test', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ref_test'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_timestamp'), 'error', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_timestamp'), table_name='error')
    op.drop_table('error')
    op.drop_index(op.f('ix_test_timestamp'), table_name='test')
    op.drop_table('test')
    op.drop_table('user')
    # ### end Alembic commands ###
