"""empty message

Revision ID: 6d8f017af70e
Revises: 592bc3ee67e0
Create Date: 2018-06-30 00:33:11.694044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8f017af70e'
down_revision = '592bc3ee67e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('errors_reported', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sign_matched', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total_tests', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total_time_taken', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_time_taken')
    op.drop_column('user', 'total_tests')
    op.drop_column('user', 'sign_matched')
    op.drop_column('user', 'errors_reported')
    op.drop_column('test', 'level')
    # ### end Alembic commands ###
